# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  backend_java:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          working_directory: ~/repo/backend_java
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          working_directory: ~/repo/backend_java
          command: mvn dependency:go-offline

      - save_cache:
          working_directory: ~/repo/webapp
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: 
          name: Backend Tests
          working_directory: ~/repo/backend_java
          command: mvn integration-test

  webapp:
    docker:
      - image: circleci/node:4.8.2
      
    
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Update npm
          working_directory: ~/repo/webapp
          command: 'sudo npm install -g npm@latest'
      
      - restore_cache:
          working_directory: ~/repo/webapp
          key: dependency-cache-{{ checksum "package.json" }}

      - run: 
          name: Install dependencies
          working_directory: ~/repo/webapp
          command: npm install
      
      - run: 
          name: run tests
          working_directory: ~/repo/webapp
          command: npm test

      - run: 
          name: build app
          working_directory: ~/repo/webapp
          command: npm run build

      - deploy:
          name: Deploy master or develop to s3
          working_directory: ~/repo/webapp/dist
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync . s3://aws-website-foodtraucker-prod-ffxtv --delete
            else if [ "${CIRCLE_BRANCH}" == "feature/InitCircleCI" ]; then
              aws s3 sync . s3://aws-website-foodtraucker-test-9th9a --delete
            fi

workflows:
  version: 2
  backend_and_frontend:
    jobs:
      - backend_java
      - webapp