package com.foodtraucker.serverless.trucks;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

/**
 * @author palmithor
 * @since 26.10.2017.
 */
@DynamoDBTable(tableName = "TABLE_CHECKINS")
public class Checkin {
    // new DynamoDBMapperConfig(new DynamoDBMapperConfig.TableNameOverride(tableName))

    private String foodtruckId;
    private String id;
    private Double lat;
    private Double lon;
    private Long checkin;
    private Long checkout;
    private Long created;


    @DynamoDBHashKey
    public String getFoodtruckId() {
        return foodtruckId;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBRangeKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public Double getLat() {
        return lat;
    }

    @DynamoDBAttribute
    public Double getLon() {
        return lon;
    }

    @DynamoDBAttribute
    public Long getCheckin() {
        return checkin;
    }

    @DynamoDBAttribute
    public Long getCheckout() {
        return checkout;
    }

    @DynamoDBAttribute
    public Long getCreated() {
        return created;
    }

    public void setId(final String id) {
        this.id = id;
    }

    public void setFoodtruckId(final String foodtruckId) {
        this.foodtruckId = foodtruckId;
    }

    public void setLat(final Double lat) {
        this.lat = lat;
    }

    public void setLon(final Double lon) {
        this.lon = lon;
    }

    public void setCheckin(final Long checkin) {
        this.checkin = checkin;
    }

    public void setCheckout(final Long checkout) {
        this.checkout = checkout;
    }

    public void setCreated(final Long created) {
        this.created = created;
    }
}
