package com.foodtraucker.serverless.trucks;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.foodtraucker.serverless.dynamo.TableEnvConstant;

/**
 * @author palmithor
 * @since 26.10.2017.
 */
@SuppressWarnings("WeakerAccess")
@DynamoDBTable(tableName = TableEnvConstant.CHECKINS_TABLE)
public class Checkin {

    private String foodtruckId;
    private String id;
    private Double lat;
    private Double lon;
    private Long checkin;
    private Long checkout;
    private Long created;
    private Long updated;

    @DynamoDBHashKey(attributeName = "foodtruck_id")
    public String getFoodtruckId() {
        return foodtruckId;
    }

    @DynamoDBRangeKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "lat")
    public Double getLat() {
        return lat;
    }

    @DynamoDBAttribute(attributeName = "lon")
    public Double getLon() {
        return lon;
    }

    @DynamoDBAttribute(attributeName = "checkin")
    public Long getCheckin() {
        return checkin;
    }

    @DynamoDBAttribute(attributeName = "checkout")
    public Long getCheckout() {
        return checkout;
    }

    @DynamoDBAttribute(attributeName = "created")
    public Long getCreated() {
        return created;
    }

    @DynamoDBAttribute(attributeName = "updated")
    public Long getUpdated() {
        return updated;
    }

    public void setFoodtruckId(final String foodtruckId) {
        this.foodtruckId = foodtruckId;
    }

    public void setId(final String id) {
        this.id = id;
    }

    public void setLat(final Double lat) {
        this.lat = lat;
    }

    public void setLon(final Double lon) {
        this.lon = lon;
    }

    public void setCheckin(final Long checkin) {
        this.checkin = checkin;
    }

    public void setCheckout(final Long checkout) {
        this.checkout = checkout;
    }

    public void setCreated(final Long created) {
        this.created = created;
    }

    public void setUpdated(final Long updated) {
        this.updated = updated;
    }
}
