package com.foodtraucker.serverless.trucks;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.foodtraucker.serverless.dynamo.TableEnvConstant;

/**
 * @author palmithor
 * @since 26.10.2017.
 */
@DynamoDBTable(tableName = TableEnvConstant.TRUCKS_TABLE)
public class Foodtruck {

    private String id;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(final String id) {
        this.id = id;
    }


}
