package com.foodtraucker.serverless.trucks;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

/**
 * @author palmithor
 * @since 26.10.2017.
 */
@DynamoDBTable(tableName = "TABLE_TRUCKS")
public class Truck {
    // new DynamoDBMapperConfig(new DynamoDBMapperConfig.TableNameOverride(tableName))

    private String id;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(final String id) {
        this.id = id;
    }

    //@DynamoDBAttribute

}
